# -*- coding: utf-8 -*-
"""Sinhala_STT_WER_Comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E_keFUlFlvR5nAHFNa60naa6ycuE_4cU

# 🎙️ Sinhala STT Model Comparison — WER Evaluation
**Research:** Adaptive Conversational Personalization and Voice Interaction Module

**Student:** Sathsara S.P.Y.B — IT22004468

**Purpose:** Compare Whisper base, small, and medium models on Sinhala speech samples and evaluate Word Error Rate (WER) to justify final model selection for the STT component.

---
### Pipeline Overview
```
Audio Input (.wav) → Whisper Model → Transcribed Text → WER Calculation → Model Comparison
```
---

## ✅ Step 1 — Check GPU Availability
Make sure you have enabled GPU in Colab:
> **Runtime → Change runtime type → T4 GPU → Save**
"""

import torch

print('='*50)
print('GPU CHECK')
print('='*50)

if torch.cuda.is_available():
    print(f'✅ GPU Available: {torch.cuda.get_device_name(0)}')
    print(f'   VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')
    DEVICE = 'cuda'
else:
    print('⚠️  No GPU detected — running on CPU (will be slower)')
    DEVICE = 'cpu'

print(f'   Device set to: {DEVICE}')
print('='*50)

"""## 📦 Step 2 — Install Required Libraries"""

print('Installing required libraries...')
print('This may take 2-3 minutes on first run.')
print('-'*50)

# Whisper — OpenAI's multilingual STT model
!pip install openai-whisper -q

# jiwer — for WER (Word Error Rate) calculation
!pip install jiwer -q

# soundfile — for reading .wav audio files
!pip install soundfile -q

# librosa — for audio processing and analysis
!pip install librosa -q

# pandas and matplotlib — for results table and chart
!pip install pandas matplotlib -q

print('\n✅ All libraries installed successfully!')

"""## 📥 Step 3 — Import Libraries"""

import whisper
import os
import time
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import soundfile as sf
import librosa
from jiwer import wer, cer
from google.colab import files
from IPython.display import Audio, display, HTML

print('✅ All imports successful!')
print(f'   Whisper version: {whisper.__version__}')

"""## 🎤 Step 4 — Upload Your Sinhala Audio Files

### What audio files do you need?
For proper research evaluation you need **at least 5 audio samples**.

**Each sample must have:**
- Format: `.wav` file
- Language: Sinhala speech
- Duration: 5 to 15 seconds each
- Clear recording (minimal background noise)
- You must know the **exact correct text** (ground truth) for WER calculation

### How to prepare audio samples:
1. Record yourself or a Sinhala speaker saying a sentence
2. Save as `.wav` format (use Audacity — free tool)
3. Write down the exact words spoken (this is your ground truth)
4. Upload all `.wav` files below

> **Important for research:** More diverse samples = stronger WER evaluation. Try different speakers, speeds, and sentence types.
"""

# ─────────────────────────────────────────────────────
# Upload your .wav audio files here
# ─────────────────────────────────────────────────────
print('Please upload your Sinhala .wav audio files.')
print('You can upload multiple files at once.')
print('-'*50)

uploaded = files.upload()

audio_files = [f for f in uploaded.keys() if f.endswith('.wav')]

print(f'\n✅ Uploaded {len(audio_files)} audio file(s):')
for i, f in enumerate(audio_files, 1):
    size = os.path.getsize(f) / 1024
    print(f'   {i}. {f}  ({size:.1f} KB)')

"""## 📝 Step 5 — Enter Ground Truth Transcriptions

**Ground Truth** = The exact correct Sinhala text that was spoken in each audio file.

This is used to calculate WER — how many words the model got wrong compared to the correct text.

**Edit the dictionary below** — add one entry per audio file.

Example format:
```python
ground_truth = {
    'sample1.wav': 'ඔබට කෙසේද',           # "How are you"
    'sample2.wav': 'මගේ නම සතසාර',        # "My name is Sathsara"
    'sample3.wav': 'ශ්‍රී ලංකාව සුන්දර රටකි', # "Sri Lanka is a beautiful country"
}
```
"""

ground_truth = {
    'sam 1(R).wav': 'මෙය සාරාංශ කරන්න',
    'sam 2(R).wav': 'මෙය තව ටිකක් විස්තර කරන්න පුළුවන්ද',
    'sam 3(R).wav': 'කරුණාකර මෙය ඉතාමත් සරලව සහ කෙටියෙන් මට තේරෙන විදිහට පහදා දෙන්න',
    'sam 4(R).wav': 'ඔයා ඔයා මට මෙහි ඇත්තේ කුමක්දැයි කියන්න පුලුවන්ද',
    'sam 5(R).wav': 'මට ඕනේ හ්ම් ඉතාමත් දිගු විස්තර නොමැතිව කෙටියෙන් වේගයෙන් මෙය පහදන්න',
    'sam 6(R).wav': 'ඒක හරියට තේරෙන්නේ නෑ වෙනත් විදිහකට කියන්න',
    'all.wav': 'මෙය සාරාංශ කරලා මෙය තව ටිකක් විස්තර කරලා කරුණාකර මෙය ඉතාමත් සරලව සහ කෙටියෙන් මට තේරෙන විදියට පහදලා ඔයා ඔයා මට මෙහි ඇත්තේ කුමක්දැයි කියලා මට ඕනේ හ්ම් ඉතාමත් දිගු විස්තර නොමැතිව කෙටියෙන් වේගයෙන් මෙය කියලා ඒක හරියට තේරෙන්නෙ නෑ වෙනත් විදිහකට කියන්න',
}

print('Ground Truth Validation')
print('='*50)
missing = []
for audio_file in audio_files:
    if audio_file in ground_truth:
        print(f'✅ {audio_file}')
        print(f'   Ground truth: "{ground_truth[audio_file]}"')
    else:
        print(f'❌ {audio_file} — MISSING ground truth!')
        missing.append(audio_file)

if missing:
    print(f'\n⚠️  Add ground truth for: {missing}')
else:
    print('\n✅ All files have ground truth. Ready to proceed!')

"""## 🔊 Step 6 — Audio Quality Check
Before transcription, verify that your audio files are properly loaded and audible.
"""

def check_audio_quality(filepath):
    """
    Loads an audio file and checks basic quality:
    - Sample rate
    - Duration
    - Peak amplitude (is it too quiet?)
    - Silence detection
    """
    try:
        audio, sr = librosa.load(filepath, sr=None)
        duration = librosa.get_duration(y=audio, sr=sr)
        peak_amplitude = np.max(np.abs(audio))
        rms = np.sqrt(np.mean(audio**2))

        # Silence detection — if RMS is very low, audio may be empty
        is_silent = rms < 0.01

        status = '⚠️  May be too quiet' if is_silent else '✅ Audio OK'

        return {
            'file': os.path.basename(filepath),
            'sample_rate': sr,
            'duration_sec': round(duration, 2),
            'peak_amplitude': round(float(peak_amplitude), 4),
            'rms_energy': round(float(rms), 4),
            'status': status
        }
    except Exception as e:
        return {'file': filepath, 'error': str(e)}


print('Audio Quality Report')
print('='*60)

for audio_file in audio_files:
    info = check_audio_quality(audio_file)
    print(f"\nFile    : {info['file']}")
    print(f"Status  : {info['status']}")
    print(f"Duration: {info['duration_sec']} seconds")
    print(f"Sample rate: {info['sample_rate']} Hz")
    print(f"Peak amplitude: {info['peak_amplitude']}")

    # Play the audio so you can hear it in Colab
    print('  ▶ Preview:')
    display(Audio(audio_file))

print('\n' + '='*60)
print('✅ Audio check complete!')

import librosa
import numpy as np

print('Audio File Diagnostics')
print('='*50)

for audio_file in audio_files:
    audio, sr = librosa.load(audio_file, sr=None)
    duration  = librosa.get_duration(y=audio, sr=sr)
    rms       = np.sqrt(np.mean(audio**2))

    print(f'\n{audio_file}')
    print(f'  Sample Rate : {sr} Hz  (Whisper needs 16000 Hz)')
    print(f'  Duration    : {duration:.2f} seconds')
    print(f'  Volume RMS  : {rms:.4f}  (below 0.01 = too quiet)')

    if sr != 16000:
        print(f'  ⚠️  Wrong sample rate — will be fixed by preprocessor')
    if rms < 0.01:
        print(f'  ⚠️  Audio too quiet — may cause hallucination')
    if duration < 1.0:
        print(f'  ⚠️  Audio too short — may cause hallucination')

import librosa
import soundfile as sf
import numpy as np
import os

print('Converting all audio files to 16000 Hz...')
print('='*50)

converted_files = []

for audio_file in audio_files:

    # Load and resample to 16000 Hz
    audio, sr = librosa.load(audio_file, sr=16000, mono=True)

    # Normalize volume
    max_val = np.max(np.abs(audio))
    if max_val > 0:
        audio = audio / max_val * 0.95

    # Save as new converted file
    converted_name = f'converted_{audio_file}'
    sf.write(converted_name, audio, 16000, subtype='PCM_16')
    converted_files.append(converted_name)

    # Verify conversion
    verify_audio, verify_sr = librosa.load(converted_name, sr=None)
    duration = librosa.get_duration(y=verify_audio, sr=verify_sr)
    rms      = np.sqrt(np.mean(verify_audio**2))

    print(f'\n✅ {audio_file} → {converted_name}')
    print(f'   Sample rate : {verify_sr} Hz')
    print(f'   Duration    : {duration:.2f} seconds')
    print(f'   Volume RMS  : {rms:.4f}')

print('\n' + '='*50)
print(f'✅ All {len(converted_files)} files converted successfully!')
print(f'   Converted files: {converted_files}')

# IMPORTANT — replace audio_files with converted files for transcription
audio_files = converted_files
print(f'\n✅ audio_files updated to use converted versions.')

import librosa
import numpy as np
import matplotlib.pyplot as plt
import IPython.display as ipd

print('Playing and visualizing your audio files...')
print('Listen carefully — can you hear your voice clearly?')
print('='*50)

for audio_file in audio_files:
    original_name = audio_file.replace('converted_', '')
    print(f'\n▶ {original_name}')

    audio, sr = librosa.load(audio_file, sr=16000)

    # Amplify for visualization only
    amplified = audio * 10

    # Plot waveform
    plt.figure(figsize=(10, 2))
    plt.plot(np.linspace(0, len(audio)/sr, len(audio)), audio)
    plt.title(f'Waveform — {original_name}')
    plt.xlabel('Time (seconds)')
    plt.ylabel('Amplitude')
    plt.tight_layout()
    plt.show()

    # Play the audio
    display(ipd.Audio(audio, rate=sr))

"""## 🤖 Step 7 — Load and Run All Three Whisper Models

This is the main evaluation step. We will:
1. Load each model (base → small → medium)
2. Transcribe all audio files with each model
3. Record transcription time
4. Calculate WER and CER for each

> **Note:** First run downloads model weights from internet. base ~140MB, small ~460MB, medium ~1.5GB. This is a one-time download per session.
"""

def transcribe_with_model(model_name, audio_files, ground_truth, device):

    print(f'\n' + '='*60)
    print(f'  MODEL: whisper-{model_name.upper()}')
    print('='*60)

    load_start = time.time()
    print(f'  Loading whisper-{model_name}...')
    model = whisper.load_model(model_name, device=device)
    load_time = time.time() - load_start
    print(f'  ✅ Model loaded in {load_time:.1f}s')

    results = []

    for audio_file in audio_files:

        # Match converted filename back to original for ground truth lookup
        original_name = audio_file.replace('converted_', '')
        if original_name not in ground_truth:
            print(f'  ⚠️  Skipping {audio_file} — no ground truth')
            continue

        ref_text = ground_truth[original_name]
        print(f'\n  ─── {original_name} ───')
        print(f'  Reference : "{ref_text}"')

        # Load audio directly as numpy array — avoids librosa warning
        audio = whisper.load_audio(audio_file)
        audio = whisper.pad_or_trim(audio)

        # Create mel spectrogram — Whisper's actual input format
        mel = whisper.log_mel_spectrogram(audio).to(device)

        # Transcribe
        t_start = time.time()
        result = model.transcribe(
            audio_file,
            language='si',
            task='transcribe',
            temperature=0.0,
            beam_size=5,
            best_of=5,
            fp16=(device == 'cuda'),
            no_speech_threshold=0.3,
            logprob_threshold=-0.5,
            compression_ratio_threshold=1.35,
            condition_on_previous_text=False,
        )
        transcription_time = time.time() - t_start

        hypothesis = result['text'].strip()
        detected_lang = result.get('language', 'unknown')

        # Hallucination detection
        words = hypothesis.split()
        is_hallucination = False

        if len(words) > 5:
            unique_words = set(words)
            if len(unique_words) <= 2:
                is_hallucination = True

        if len(hypothesis) > 10:
            chars = list(hypothesis.replace(' ', ''))
            unique_chars = set(chars)
            if len(unique_chars) <= 2:
                is_hallucination = True

        if is_hallucination:
            print(f'  ⚠️  Hallucination detected!')
            hypothesis = '[HALLUCINATION — model failed on this sample]'
            word_error_rate = 1.0
            char_error_rate = 1.0
        else:
            word_error_rate = wer(ref_text, hypothesis)
            char_error_rate = cer(ref_text, hypothesis)

        print(f'  Whisper output : "{hypothesis}"')
        print(f'  WER  : {word_error_rate*100:.2f}%')
        print(f'  CER  : {char_error_rate*100:.2f}%')
        print(f'  Time : {transcription_time:.2f}s')
        print(f'  Lang : {detected_lang}')

        results.append({
            'model'                 : f'whisper-{model_name}',
            'audio_file'            : original_name,
            'reference'             : ref_text,
            'whisper_transcription' : hypothesis,
            'wer'                   : round(word_error_rate, 4),
            'wer_percent'           : round(word_error_rate * 100, 2),
            'cer'                   : round(char_error_rate, 4),
            'cer_percent'           : round(char_error_rate * 100, 2),
            'transcription_time_sec': round(transcription_time, 2),
            'detected_language'     : detected_lang,
            'hallucination'         : is_hallucination
        })

    del model
    if device == 'cuda':
        torch.cuda.empty_cache()

    return results


# ── Run all 3 models ──────────────────────────────────
all_results = []

for model_name in ['base', 'small', 'medium']:
    model_results = transcribe_with_model(
        model_name   = model_name,
        audio_files  = audio_files,
        ground_truth = ground_truth,
        device       = DEVICE
    )
    all_results.extend(model_results)

print('\n' + '='*60)
print('✅ All three models finished — WER calculated!')
print('='*60)

"""## 📊 Step 8 — Results Table
View the full detailed results for every model and every audio sample.
"""

# Create a DataFrame from all results
df = pd.DataFrame(all_results)

# Display full results table
print('Full Results Table')
print('='*80)
display(df[[
    'model', 'audio_file', 'reference', 'whisper_transcription',
    'wer_percent', 'cer_percent', 'transcription_time_sec'
]])

# ─────────────────────────────────────────────────────
# Summary — Average WER, CER, Time per model
# ─────────────────────────────────────────────────────
print('\n\nModel Summary (Averages Across All Samples)')
print('='*60)

summary = df.groupby('model').agg(
    avg_wer_percent=('wer_percent', 'mean'),
    avg_cer_percent=('cer_percent', 'mean'),
    avg_time_sec=('transcription_time_sec', 'mean'),
    total_samples=('audio_file', 'count')
).reset_index()

summary['avg_wer_percent'] = summary['avg_wer_percent'].round(2)
summary['avg_cer_percent'] = summary['avg_cer_percent'].round(2)
summary['avg_time_sec']    = summary['avg_time_sec'].round(2)

# Sort by WER ascending (best model first)
summary = summary.sort_values('avg_wer_percent')

display(summary)

# Identify best model
best_model = summary.iloc[0]['model']
best_wer   = summary.iloc[0]['avg_wer_percent']
print(f'\n🏆 Best Model: {best_model} with Average WER of {best_wer}%')

"""## 📈 Step 9 — Visualization Charts
Generate charts for your research paper.
"""

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.suptitle(
    'Whisper Model Comparison — Sinhala STT Evaluation\n'
    'Adaptive Conversational Personalization and Voice Interaction Module (R26-DS-002)',
    fontsize=12, fontweight='bold', y=1.02
)

models     = summary['model'].tolist()
wer_vals   = summary['avg_wer_percent'].tolist()
cer_vals   = summary['avg_cer_percent'].tolist()
time_vals  = summary['avg_time_sec'].tolist()

colors = ['#4B6CB7', '#74B9FF', '#0984E3']

# ─── Chart 1: WER Comparison ───
bars1 = axes[0].bar(models, wer_vals, color=colors, edgecolor='white', linewidth=0.5)
axes[0].set_title('Word Error Rate (WER %)', fontweight='bold')
axes[0].set_ylabel('WER (%)')
axes[0].set_ylim(0, max(wer_vals) * 1.3 if max(wer_vals) > 0 else 100)
for bar, val in zip(bars1, wer_vals):
    axes[0].text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 0.5,
        f'{val:.2f}%',
        ha='center', va='bottom', fontsize=10, fontweight='bold'
    )
axes[0].set_facecolor('#F8F9FA')
axes[0].spines['top'].set_visible(False)
axes[0].spines['right'].set_visible(False)
axes[0].annotate('← Lower is better', xy=(0.5, -0.15), xycoords='axes fraction',
                 ha='center', fontsize=9, color='gray')

# ─── Chart 2: CER Comparison ───
bars2 = axes[1].bar(models, cer_vals, color=colors, edgecolor='white', linewidth=0.5)
axes[1].set_title('Character Error Rate (CER %)', fontweight='bold')
axes[1].set_ylabel('CER (%)')
axes[1].set_ylim(0, max(cer_vals) * 1.3 if max(cer_vals) > 0 else 100)
for bar, val in zip(bars2, cer_vals):
    axes[1].text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 0.5,
        f'{val:.2f}%',
        ha='center', va='bottom', fontsize=10, fontweight='bold'
    )
axes[1].set_facecolor('#F8F9FA')
axes[1].spines['top'].set_visible(False)
axes[1].spines['right'].set_visible(False)
axes[1].annotate('← Lower is better', xy=(0.5, -0.15), xycoords='axes fraction',
                 ha='center', fontsize=9, color='gray')

# ─── Chart 3: Transcription Speed ───
bars3 = axes[2].bar(models, time_vals, color=colors, edgecolor='white', linewidth=0.5)
axes[2].set_title('Avg Transcription Time (seconds)', fontweight='bold')
axes[2].set_ylabel('Time (sec)')
axes[2].set_ylim(0, max(time_vals) * 1.3 if max(time_vals) > 0 else 30)
for bar, val in zip(bars3, time_vals):
    axes[2].text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 0.1,
        f'{val:.2f}s',
        ha='center', va='bottom', fontsize=10, fontweight='bold'
    )
axes[2].set_facecolor('#F8F9FA')
axes[2].spines['top'].set_visible(False)
axes[2].spines['right'].set_visible(False)
axes[2].annotate('← Lower is better', xy=(0.5, -0.15), xycoords='axes fraction',
                 ha='center', fontsize=9, color='gray')

plt.tight_layout()
plt.savefig('wer_comparison_chart.png', dpi=300, bbox_inches='tight')
plt.show()

print('✅ Chart saved as wer_comparison_chart.png')

"""## 📊 Step 10 — Per-Sample WER Chart
Compare how each model performed on each individual audio sample.
"""

fig2, ax = plt.subplots(figsize=(14, 6))

model_names  = df['model'].unique()
sample_names = df['audio_file'].unique()
x            = np.arange(len(sample_names))
width        = 0.25
bar_colors   = ['#4B6CB7', '#74B9FF', '#0984E3']

for i, (model_name, color) in enumerate(zip(model_names, bar_colors)):
    model_df = df[df['model'] == model_name]
    wer_values = []
    for sample in sample_names:
        sample_row = model_df[model_df['audio_file'] == sample]
        wer_values.append(sample_row['wer_percent'].values[0] if len(sample_row) > 0 else 0)
    ax.bar(x + i * width, wer_values, width, label=model_name, color=color, edgecolor='white')

ax.set_xlabel('Audio Sample', fontsize=11)
ax.set_ylabel('WER (%)', fontsize=11)
ax.set_title(
    'Per-Sample WER Comparison Across All Whisper Models\nSinhala Speech Recognition Evaluation',
    fontsize=12, fontweight='bold'
)
ax.set_xticks(x + width)
ax.set_xticklabels(sample_names, rotation=30, ha='right')
ax.legend()
ax.set_facecolor('#F8F9FA')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.savefig('per_sample_wer_chart.png', dpi=300, bbox_inches='tight')
plt.show()

print('✅ Per-sample chart saved as per_sample_wer_chart.png')

"""## 🏆 Step 11 — Final Research Evaluation Report
This section generates a structured evaluation report suitable for inclusion in your research paper.
"""

print('='*70)
print('  SINHALA STT MODEL EVALUATION REPORT')
print('  Adaptive Conversational Personalization and Voice Interaction Module')
print('  Component 4 — Speech-to-Text Evaluation')
print('  Student: Sathsara S.P.Y.B | IT22004468 | R26-DS-002')
print('='*70)

print(f'\n  Total audio samples evaluated : {len(audio_files)}')
print(f'  Models compared               : whisper-base, whisper-small, whisper-medium')
print(f'  Language                      : Sinhala (si)')
print(f'  Evaluation metrics            : WER (Word Error Rate), CER (Character Error Rate)')
print(f'  Hardware                      : {torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU"}')

print('\n' + '-'*70)
print('  MODEL PERFORMANCE SUMMARY')
print('-'*70)

for _, row in summary.iterrows():
    rank_label = '🥇 BEST' if row['model'] == best_model else '     '
    print(f"\n  {rank_label} {row['model'].upper()}")
    print(f"    Average WER : {row['avg_wer_percent']}%  ({'lower is better'}")
    print(f"    Average CER : {row['avg_cer_percent']}%")
    print(f"    Avg Speed   : {row['avg_time_sec']}s per sample")

print('\n' + '-'*70)
print('  RESEARCH CONCLUSION')
print('-'*70)

best_wer_val = summary[summary['model'] == best_model]['avg_wer_percent'].values[0]
best_cer_val = summary[summary['model'] == best_model]['avg_cer_percent'].values[0]
best_time    = summary[summary['model'] == best_model]['avg_time_sec'].values[0]

print(f"""
  Based on the comparative evaluation of three Whisper model variants
  on Sinhala speech samples, {best_model} achieved the lowest
  Word Error Rate (WER) of {best_wer_val}% and Character Error Rate (CER)
  of {best_cer_val}%, with an average transcription time of {best_time} seconds
  per audio sample.

  Therefore, {best_model} is selected as the Speech-to-Text backbone
  for the Adaptive Conversational Personalization and Voice Interaction
  Module (ACP-VIM), as it demonstrates the highest accuracy for
  Sinhala speech recognition among the evaluated models.

  Note: All three Whisper models are fully pre-trained and require
  no additional fine-tuning or labeled Sinhala datasets for deployment,
  making them directly applicable to the low-resource Sinhala language
  scenario described in Section 1.3 of the project proposal.
""")

print('='*70)

"""## 💾 Step 12 — Save and Download All Results"""

# Save detailed results to CSV
df.to_csv('stt_evaluation_results.csv', index=False, encoding='utf-8-sig')

# Save summary to CSV
summary.to_csv('stt_evaluation_summary.csv', index=False, encoding='utf-8-sig')

# Save results as JSON (useful for further processing)
with open('stt_evaluation_results.json', 'w', encoding='utf-8') as f:
    json.dump(all_results, f, ensure_ascii=False, indent=2)

print('Files saved:')
print('  ✅ stt_evaluation_results.csv   — Full per-sample results')
print('  ✅ stt_evaluation_summary.csv   — Model averages summary')
print('  ✅ stt_evaluation_results.json  — Full results in JSON')
print('  ✅ wer_comparison_chart.png     — Main comparison chart')
print('  ✅ per_sample_wer_chart.png     — Per-sample comparison chart')

print('\nDownloading all result files...')

files.download('stt_evaluation_results.csv')
files.download('stt_evaluation_summary.csv')
files.download('stt_evaluation_results.json')
files.download('wer_comparison_chart.png')
files.download('per_sample_wer_chart.png')

print('\n✅ All files downloaded to your computer!')
print('   Use the charts and CSV files directly in your research paper.')

"""---
## 📌 How to Use These Results in Your Research Paper

### Section 3.5 — Validation Strategy and Performance Metrics
You can write:

> *"A comparative evaluation of three Whisper model variants (base, small, and medium) was conducted on [N] Sinhala speech samples. The models were evaluated using Word Error Rate (WER) and Character Error Rate (CER) metrics. Whisper-medium achieved the lowest WER of [X]%, demonstrating superior accuracy for Sinhala speech recognition compared to whisper-small ([Y]% WER) and whisper-base ([Z]% WER). Based on this evaluation, whisper-medium was selected as the Speech-to-Text module for the Adaptive Conversational Personalization and Voice Interaction Module."*

### Include in your paper:
- `wer_comparison_chart.png` — as Figure in evaluation section
- `stt_evaluation_summary.csv` — as Table in evaluation section
- The conclusion paragraph from Step 11

---
**Next Step after this notebook:**
Move to VS Code and build the full pipeline using whisper-small locally, or use the Hugging Face API for whisper-medium.
"""