# -*- coding: utf-8 -*-
"""Google STT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FyYB7o5HiAtWtEw23vV9UqSzUX9GtMe5
"""

from google.colab import drive
try:
    drive.mount('/content/drive', force_remount=True)
    print('✅ Drive mounted successfully!')
except Exception as e:
    print(f'❌ Mount failed: {e}')

# ─── Install & Imports ────────────────────────────────
!pip install SpeechRecognition jiwer -q
!apt-get install -y ffmpeg -q

import speech_recognition as sr
from jiwer import wer, cer
import librosa
import soundfile as sf
import numpy as np
import os

# ─────────────────────────────────────────────────────
# 👇 CHANGE THIS to your actual Google Drive folder path
# Example: '/content/drive/MyDrive/sinhala_audio'
#          '/content/drive/MyDrive/STT_samples'
#          '/content/drive/MyDrive/'  ← if files are in root
# ─────────────────────────────────────────────────────
AUDIO_FOLDER = '/content/drive/MyDrive/Voice_Samples/real'

# ─── Verify folder exists and show files found ────────
print('='*60)
print('AUDIO FILES CHECK')
print('='*60)

if not os.path.exists(AUDIO_FOLDER):
    print(f'❌ Folder not found: {AUDIO_FOLDER}')
    print('   Check your Google Drive folder name and update AUDIO_FOLDER above.')
else:
    found_files = [f for f in os.listdir(AUDIO_FOLDER) if f.endswith('.wav')]
    print(f'✅ Folder found: {AUDIO_FOLDER}')
    print(f'✅ WAV files found: {len(found_files)}')
    for f in found_files:
        size = os.path.getsize(os.path.join(AUDIO_FOLDER, f)) / 1024
        print(f'   📁 {f}  ({size:.1f} KB)')

# ─── Ground Truth ─────────────────────────────────────
# Update these with your NEW 6 recordings and what you said
ground_truth = {
    'sam 1(R).wav': 'මෙය සාරාංශ කරන්න',
    'sam 2(R).wav': 'මෙය තව ටිකක් විස්තර කරන්න පුළුවන්ද',
    'sam 3(R).wav': 'කරුණාකර මෙය ඉතාමත් සරලව සහ කෙටියෙන් මට තේරෙන විදිහට පහදා දෙන්න',
    'sam 4(R).wav': 'ඔයා ඔයා මට මෙහි ඇත්තේ කුමක්දැයි කියන්න පුලුවන්ද',
    'sam 5(R).wav': 'මට ඕනේ හ්ම් ඉතාමත් දිගු විස්තර නොමැතිව කෙටියෙන් වේගයෙන් මෙය පහදන්න',
    'sam 6(R).wav': 'ඒක හරියට තේරෙන්නේ නෑ වෙනත් විදිහකට කියන්න',
    'all.wav': 'මෙය සාරාංශ කරලා මෙය තව ටිකක් විස්තර කරලා කරුණාකර මෙය ඉතාමත් සරලව සහ කෙටියෙන් මට තේරෙන විදියට පහදලා ඔයා ඔයා මට මෙහි ඇත්තේ කුමක්දැයි කියලා මට ඕනේ හ්ම් ඉතාමත් දිගු විස්තර නොමැතිව කෙටියෙන් වේගයෙන් මෙය කියලා ඒක හරියට තේරෙන්නෙ නෑ වෙනත් විදිහකට කියන්න',
}

# ─── Convert audio to 16000Hz before STT ──────────────
def convert_audio(input_path):
    """Convert any wav to 16000Hz mono — required for Google STT."""
    audio, sr_rate = librosa.load(input_path, sr=16000, mono=True)
    max_val = np.max(np.abs(audio))
    if max_val > 0:
        audio = audio / max_val * 0.95
    converted_path = f'/content/converted_{os.path.basename(input_path)}'
    sf.write(converted_path, audio, 16000, subtype='PCM_16')
    return converted_path

# ─── Main STT Loop ─────────────────────────────────────
recognizer = sr.Recognizer()
results     = {}

print('\n' + '='*60)
print('Google STT — Sinhala Speech Recognition (si-LK)')
print('='*60)

for filename, ref_text in ground_truth.items():

    full_path = os.path.join(AUDIO_FOLDER, filename)

    # Check file exists
    if not os.path.exists(full_path):
        print(f'\n❌ File not found: {full_path}')
        print(f'   Make sure {filename} is in your Drive folder.')
        results[filename] = ''
        continue

    print(f'\n{"─"*55}')
    print(f'  File      : {filename}')
    print(f'  Reference : {ref_text}')

    try:
        # Step 1 — Convert to correct format
        converted = convert_audio(full_path)

        # Step 2 — Load into recognizer
        with sr.AudioFile(converted) as source:
            recognizer.adjust_for_ambient_noise(source, duration=0.3)
            audio_data = recognizer.record(source)

        # Step 3 — Google STT in Sinhala
        transcribed = recognizer.recognize_google(
            audio_data,
            language='si-LK'
        )

        # Step 4 — Calculate WER and CER
        word_error_rate = wer(ref_text, transcribed)
        char_error_rate = cer(ref_text, transcribed)

        results[filename] = transcribed

        print(f'  Google STT: {transcribed}')
        print(f'  WER       : {word_error_rate*100:.2f}%')
        print(f'  CER       : {char_error_rate*100:.2f}%')

        # Clean up converted file
        os.remove(converted)

    except sr.UnknownValueError:
        print(f'  ⚠️  Could not understand audio')
        print(f'      → Try re-recording more clearly')
        results[filename] = ''

    except sr.RequestError as e:
        print(f'  ❌ API error: {e}')
        results[filename] = ''

# ─── Summary ───────────────────────────────────────────
print('\n' + '='*60)
print('SUMMARY')
print('='*60)

successful = sum(1 for v in results.values() if v != '')
print(f'  Successfully transcribed : {successful}/{len(ground_truth)} files')
print(f'  Failed                   : {len(ground_truth)-successful}/{len(ground_truth)} files')

print('\n  Results saved in: results dictionary')
print('  Next step: Intent Detection on these transcriptions')
print('='*60)