# -*- coding: utf-8 -*-
"""STT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HOvQ_kASXA-EwrlnV6s7mqZ1NyPKSYl-
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install transformers
!pip install torchaudio
!pip install librosa
!pip install soundfile

import torch
import librosa
import soundfile as sf
from transformers import AutoProcessor, Wav2Vec2BertForCTC

model_name = "L-Inuri/Wav2Vec-BERT"

print("Loading processor...")
processor = AutoProcessor.from_pretrained(model_name)

print("Loading model...")
model = Wav2Vec2BertForCTC.from_pretrained(model_name)

model.eval()
print("✅ Model loaded successfully!")

from google.colab import files

print("Upload your Sinhala audio file (.wav or .mp3)")
uploaded = files.upload()

# Get the uploaded filename
audio_filename = list(uploaded.keys())[0]
print(f"✅ Uploaded file: {audio_filename}")

import librosa

# Store all processed audio arrays
audio_data = {}

for filename in uploaded.keys():
    print(f"Loading: {filename}")

    # Load and resample each file to 16kHz
    audio_array, sampling_rate = librosa.load(filename, sr=16000, mono=True)

    audio_data[filename] = audio_array

    print(f"   ✅ Loaded successfully!")
    print(f"   Sample rate : {sampling_rate} Hz")
    print(f"   Duration    : {len(audio_array)/sampling_rate:.2f} seconds")
    print("-" * 40)

print(f"\n✅ Total files loaded: {len(audio_data)}")

# Run Speech to Text on all loaded files
print("=" * 50)
print("📝 Transcription Results:")
print("=" * 50)

all_transcriptions = {}

for filename, audio_array in audio_data.items():

    # Process the audio
    inputs = processor(
        audio_array,
        sampling_rate=16000,
        return_tensors="pt",
        padding=True
    )

    # Run inference
    with torch.no_grad():
        logits = model(**inputs).logits

    # Decode the output
    predicted_ids = torch.argmax(logits, dim=-1)
    transcription = processor.batch_decode(predicted_ids)

    all_transcriptions[filename] = transcription[0]

    print(f"File : {filename}")
    print(f"Text : {transcription[0]}")
    print("-" * 40)

"""#Other Model"""

from transformers import WhisperProcessor, WhisperForConditionalGeneration
import torch

print("Loading Whisper Small Sinhala model...")

whisper_processor = WhisperProcessor.from_pretrained(
    "Lingalingeswaran/whisper-small-sinhala"
)
whisper_model = WhisperForConditionalGeneration.from_pretrained(
    "Lingalingeswaran/whisper-small-sinhala"
)

# Fix for newer transformers — disable forced_decoder_ids from config
whisper_model.generation_config.forced_decoder_ids = None
whisper_model.generation_config.suppress_tokens = []

whisper_model.eval()
print("✅ Whisper Small Sinhala model loaded!")

import soundfile as sf

print("=" * 50)
print("📝 Whisper Small Sinhala Results:")
print("=" * 50)

whisper_transcriptions = {}

for filename, audio_array in audio_data.items():

    # Process audio
    inputs = whisper_processor(
        audio_array,
        sampling_rate=16000,
        return_tensors="pt"
    )

    # Generate transcription — language forced via generate kwargs
    with torch.no_grad():
        predicted_ids = whisper_model.generate(
            inputs["input_features"],
            language="si",
            task="transcribe"
        )

    # Decode output
    whisper_text = whisper_processor.batch_decode(
        predicted_ids,
        skip_special_tokens=True
    )[0].strip()

    whisper_transcriptions[filename] = whisper_text

    print(f"File : {filename}")
    print(f"Text : {whisper_text}")
    print("-" * 40)

print(f"\n✅ Total files transcribed: {len(whisper_transcriptions)}")

print("=" * 70)
print("📊 COMPARISON: Wav2Vec2-BERT  vs  Whisper-Small-Sinhala")
print("=" * 70)

for filename in audio_data.keys():
    wav2vec_text  = all_transcriptions.get(filename, "N/A")
    whisper_text  = whisper_transcriptions.get(filename, "N/A")

    print(f"\n🎙️  File          : {filename}")
    print(f"🔵 Wav2Vec-BERT  : {wav2vec_text}")
    print(f"🟡 Whisper-Small : {whisper_text}")
    print("-" * 70)

print("\n✅ Comparison complete!")

# Add your actual correct transcriptions here to measure accuracy
ground_truth = {
    'sample1.wav': 'මෙය තව ටිකක් විස්තර කරන්න පුලුවන්ද',
    'sample2.wav': 'සරලව හෙමින් කියන්න',
    'sample3.wav': 'කරුණාකර මෙය සාරාංශ ගතකර දෙන්න',
    'sample4.wav': 'මෙහි ඇත්තේ කුමක්දැයි පහදන්න',
    'sample5.wav': 'ඉතාමත් දිගු විස්තර කිරීම් නොමැතිව කෙටියෙන් වේගයෙන් පහදන්න'
}

print("=" * 70)
print("🎯 ACCURACY CHECK")
print("=" * 70)

wav2vec_correct  = 0
whisper_correct  = 0
total = 0

for filename, correct_text in ground_truth.items():
    if filename not in audio_data:
        continue

    wav2vec_text = all_transcriptions.get(filename, "")
    whisper_text = whisper_transcriptions.get(filename, "")

    # Simple exact match check
    w2v_match = "✅" if wav2vec_text.strip() == correct_text.strip() else "❌"
    whi_match = "✅" if whisper_text.strip() == correct_text.strip() else "❌"

    if wav2vec_text.strip() == correct_text.strip():
        wav2vec_correct += 1
    if whisper_text.strip() == correct_text.strip():
        whisper_correct += 1
    total += 1

    print(f"\n🎙️  File            : {filename}")
    print(f"📌 Correct          : {correct_text}")
    print(f"🔵 Wav2Vec-BERT {w2v_match} : {wav2vec_text}")
    print(f"🟡 Whisper-Small {whi_match}: {whisper_text}")
    print("-" * 70)

if total > 0:
    print(f"\n📈 Wav2Vec-BERT  Accuracy : {wav2vec_correct}/{total} ({wav2vec_correct/total*100:.1f}%)")
    print(f"📈 Whisper-Small Accuracy : {whisper_correct}/{total} ({whisper_correct/total*100:.1f}%)")